// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0g6aYfHix0NpAawj_2s4D5YdlthS-xNo',
    appId: '1:784829337277:web:d478ceeefa2d0624b7f1d4',
    messagingSenderId: '784829337277',
    projectId: 'coffeeshop-90589',
    authDomain: 'coffeeshop-90589.firebaseapp.com',
    storageBucket: 'coffeeshop-90589.firebasestorage.app',
    measurementId: 'G-Q1PPNWLKG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPsrq6Ijl30JkIN-s4Ja2vH88aOojPd2w',
    appId: '1:784829337277:android:e9d8c6ac9cc69303b7f1d4',
    messagingSenderId: '784829337277',
    projectId: 'coffeeshop-90589',
    storageBucket: 'coffeeshop-90589.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1dSyNKeEAmYj_JLwP4D1HAMUfuQ23Nls',
    appId: '1:784829337277:ios:e7e87680ed3563adb7f1d4',
    messagingSenderId: '784829337277',
    projectId: 'coffeeshop-90589',
    storageBucket: 'coffeeshop-90589.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShopp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1dSyNKeEAmYj_JLwP4D1HAMUfuQ23Nls',
    appId: '1:784829337277:ios:e7e87680ed3563adb7f1d4',
    messagingSenderId: '784829337277',
    projectId: 'coffeeshop-90589',
    storageBucket: 'coffeeshop-90589.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShopp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0g6aYfHix0NpAawj_2s4D5YdlthS-xNo',
    appId: '1:784829337277:web:d58db8b66b2425fab7f1d4',
    messagingSenderId: '784829337277',
    projectId: 'coffeeshop-90589',
    authDomain: 'coffeeshop-90589.firebaseapp.com',
    storageBucket: 'coffeeshop-90589.firebasestorage.app',
    measurementId: 'G-K7EYHKKVL3',
  );
}
